### PR TITLE
Fix uninitialized fmpz in fq_multiplicative_order

### PR DESCRIPTION
**Pull request by albinahlback**
This should fix it, right? @fredrik-johansson

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
I already pushed a fix! (I think.)

**Comment by fredrik-johansson** [comment]
That doesn't matter. And you have a potential memory leak in your version :-)

**Comment by albinahlback** [comment]
I cannot see it at a first glance, where is it?

**Comment by fredrik-johansson** [comment]
There are three init calls without corresponding clears when the is_zero branch is taken.

**Comment by fredrik-johansson** [comment]
BTW, the original code also looks dubious setting ``ord`` to an alias for ``tmp``, but then in the main loop ``ord`` and ``tmp`` are used as separate variables...

**Comment by albinahlback** [comment]
How about this?

**Comment by albinahlback** [comment]
Yes!

**Pull request merged**
