### PR TITLE
Group declaration of struct into `fmpz_types.h`

### PR DESCRIPTION
**Pull request by albinahlback**
Is this good? I did not include `fmpz_lll` as I believe that is rarely used, and could not be considered a "basic" type. I also did not include `fmpz_mod*` as I consider that another type.

### CODE REVIEW

**Comment by albinahlback** [comment]
I don't know if you want `fmpzi` in there. I included it.

**Comment by fredrik-johansson** [comment]
This looks good. Could you do ``fmpq`` too?

We also need ``fmpz_mpoly_ctx_t`` et al. since most ``fmpz_mpoly`` functions require a context object as input. I think the easiest way to allow declaring mpoly context types without including ``mpoly.h`` is to move ``ordering_t`` and ``mpoly_ctx_struct``/``mpoly_ctx_t`` into ``flint.h``. Does that make sense?

**Comment by albinahlback** [comment]
Yeah, I intend to make a complete PR for all the types. I will let you know if it makes sense when I am sitting with it again; currently I am merging template files :-)

**Comment by albinahlback** [comment]
Reminder to self: I think on has to add the new headers to `Makefile.in`.

**Comment by albinahlback** [comment]
@fredrik-johansson You don't think it makes more sense to have like `mpoly_types.h`? In my opinion, that bloats `flint.h`. (Not saying this is the best option, just my feeling at the moment.)

**Comment by fredrik-johansson** [comment]
Yeah, you can try that.

**Comment by albinahlback** [comment]
Let me know what you think of this. Although some `*_types.h` have to include other `*_types.h` headers, I think this was solved in a nice manner as now `fmpz` and `fmpq` are both in `flint.h`.

I also added `nmod_t` into `flint.h`, which I think fits very nice.

I also created one for all arb types as well, as I think they are "base" types just like `fmpz`. Two notes regarding this:
- I inserted `mag` into `arb_types.h` as, in my opinion, `mag` and `arb` are inseperable (one does not use `mag` on its own).
- I had to include `#define ARF_NOPTR_LIMBS 2` into `arf_types.h` as it otherwise would not work. However, I see this constant as more of a helper constant as opposed to some constant that is configurable; it is exactly 2 in order for `sizeof(mantissa_noptr_struct) == sizeof(mantissa_ptr_struct)`.

(Let me know if you have other opinions regarding this.)

It would be nice to create similar headers for the `fq` stuff, but that is future work in that case. As of now, I am happy with this.

**Comment by fredrik-johansson** [comment]
Probably some tweaks can be made but let's experiment with this.

**Pull request merged**
