### PR TITLE
Make makeover

### PR DESCRIPTION
**Pull request by albinahlback**
**NOTE: I am currently in the state of testing this PR.**

- [x] `make` with only shared enabled
- [x] `make` with only static enabled
- [x] `make` with both shared and static enabled
- [x] `make install`
- [x] `make uninstall`
- [x] `make clean`
- [x] `make distclean`
- [x] `make check` with only shared enabled (should work now)
- [x] `make check` with only static enabled
- [x] `make check MOD=...` with only shared enabled
- [x] `make check MOD=...` with only static enabled
- [x] `make tests`
- [x] `make && make tests && touch src/fmpz/add.c && make check` with only static enabled should build the tests twice
- [x] `make profile` (although some do not work, such as `fq_poly/profile/p-gcd.c`)
- [x] `make examples`
- [x] `make && touch src/flint.h && make` should rebuild the library
- [ ] `make tune` (I will not check this personally)
- [ ] `make valgrind` (I will not check this personally)
- [ ] `make dist` (I will not check this personally)

## Description

I have wanted to make a complete makeover of `Makefile.in` for a while now, so here it is.

Here is the timings of calling `make -j` on an Intel i5-6300U in a clean directory:
```
Old version
real    6m25.242s
user    21m34.224s
sys     2m33.245s

New version
real    6m18.547s
user    22m22.414s
sys     2m20.165s
```
This equates to about 1.8% speedup that only comes from altering the makefile. Moreover, the i5-6300U has 4 threads. A larger relative speedup is to be expected the more amount of threads you have.  

My feeling is that the current makefile has grown to be something incoherent, and so I did the makeover with the following things in mind.

### Avoid MAKE calls within the makefile
Although not bad as a concept, I do not think it was implemented in a good way. For example, currently `libflint.a` depends on the sources `*.c`, but in a makefile it should depend on the objects `*.o` which in turn depends on the sources.

I also like that it does not changes the directory multiple times, and as a consequence does not print stuff like
```
make[2]: Entering directory '/home/albin/cpkg/flint2/src/ca_mat'
make[2]: Leaving directory '/home/albin/cpkg/flint2/src/ca_mat'
make[1]: Leaving directory '/home/albin/cpkg/flint2'
```

### Mainly rely on Make's own language
Currently a lot of shell code is invoked. One example of this is the multiple
```Make
myrecipe:
	if [ "$(MY_VAR)" -eq "1" ]; then \
		DO SOMETHING; \
	fi
```
Instead, I think that one should utilize Make's own conditionals, such as `ifeq`.

A major part was to change all of these shell conditionals to Make conditionals.

### Write proper dependencies

As mentioned in the first point, recipes did not have the proper dependencies. This was now fixed.

### Enable building specific files

I believe that one should be able to build specific files, such as via `make build/fmpz/test/t-add`. This is currently not possible. I wrote recipes such that one can build any specific file they want to, and that these have proper dependencies.

Taking the example of the library object file `build/fmpz/test/t-add`, it requires that the directory `build/fmpz/test` exists and that some library exists of FLINT. It depends on `src/fmpz/test/t-add.c`, but also on `libflint.a` if one only builds static library. If one also builds the shared library, then we only require that `$(FLINT_LIB)` exists.

### Faster multithreaded builds

Currently, when the makefile calls on `Makefile.subdirs`, it has to wait for all the files to be completed before going back to `Makefile`. This is also the case when building multithreaded, such as via `make -j`. As such, time is wasted, which is now fixed due to one single makefile with no `MAKE` calls.

### Time of initialization

As many evaluations has to be made during the initialization process when calling `make`, it takes a little bit longer to call on the makefile in some cases.

The timing for `make print-BUILD_DIR` changes the following way:
```
Old version
real    0m0.076s
user    0m0.068s
sys     0m0.007s

New version (clean slate)
real    0m0.078s
user    0m0.064s
sys     0m0.014s

New version (after building the library)
real    0m4.410s
user    0m4.225s
sys     0m0.176s
```
The reason for this is the amount of inclusions of `*.d`-files (assuming that you have `WANT_DEPS=1`, otherwise this is not a problem). If you have built the library, there is a lot of them, which will take some time to go through. If anyone has any solution for this, it would be nice to hear it.

### Expansions are gone

I did not include any possibilities to utilize expansions in this remake. Honestly, I do not see any reason to why one would like to use expansions. FLINT does not have many private functions, so having expansions versus building a new project should not be different. If this is important to someone, please let me know, and I will add it.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
This actually speeds up a clean ``make -j`` more than 25% for me: down from 1min33s to 1min13s.

A minimal rebuild (``touch fmpz/add.c && time make -j``) is a bit slower: 3.8 seconds instead of 3.2 seconds. That's not too bad.

The delay for ``make check`` could be a bit annoying though. With the old Makefile ``make -j check MOD=nf`` takes <0.5 seconds but here it takes 2.5 seconds. I appreciate having a quick compile-check cycle so it would be great if there is some way to fix this.

**Comment by albinahlback** [comment]
> This actually speeds up a clean `make -j` more than 25% for me: down from 1min33s to 1min13s.

Wow, that's even more than I thought was possible!

> The delay for `make check` could be a bit annoying though. With the old Makefile `make -j check MOD=nf` takes <0.5 seconds but here it takes 2.5 seconds. I appreciate having a quick compile-check cycle so it would be great if there is some way to fix this.

And what happens if you set `WANT_DEPS=0`? Is it fast in that case? Anyway, while fixing some bugs I will think of a way to fix this. Will probably do something with `MAKECMDGOALS`.

**Comment by fredrik-johansson** [comment]
It's a problem that ``make check`` no longer gives any indication which module each test belongs to.

**Comment by fredrik-johansson** [comment]
> Wow, that's even more than I thought was possible!

Well, I've managed that kind of speedup myself too... when I accidentally disabled ``-O2`` before rebuilding. So I hope you're not cheating ;-)

**Comment by fredrik-johansson** [comment]
> And what happens if you set WANT_DEPS=0? Is it fast in that case?

It is, but the lack of dependency tracking is sort of a big drawback...

**Comment by albinahlback** [comment]
> > And what happens if you set WANT_DEPS=0? Is it fast in that case?
> 
> It is, but the lack of dependency tracking is sort of a big drawback...

Yeah, just wanted to make sure that this indeed is the problem.

**Comment by albinahlback** [comment]
I added a list of what has to be checked (also noted what points I will not check).

**Comment by fredrik-johansson** [comment]
BTW, something Bill suggested in the past was to build a merged object file for each module, then merge the module object files to make libflint.

Not sure if this would help with faster rebuilds.

Using ``mold`` instead of the GNU linker also saves a second or so.

**Comment by albinahlback** [comment]
> BTW, something Bill suggested in the past was to build a merged object file for each module, then merge the module object files to make libflint.
> 
> Not sure if this would help with faster rebuilds.

I have never noticed that creating `libflint.a` or `libflint.so` more than, say, five seconds. Previously, it actually did that for `.lo` files, but not for `.o` files. But as mentioned, you would not really benefit from this. I think it would just be faster and simpler to merge source files in this case.

> Using `mold` instead of the GNU linker also saves a second or so.

Yeah, but the bottleneck should be the amount of inclusions as well as the amount of files that are being compiled.

**Comment by albinahlback** [comment]
I have now checked everything I am going to check in my list. I will now think of a way to not include `*.d` files in some scenarios.

**Comment by albinahlback** [comment]
I think the following is the best method for avoiding to include `.d` files. I also want to point out that I also added dependency tracking for executables, such as the tests, which I think this is important. For example, if one changes `flint.h`, then every test has to be recompiled.

For simplicity, I will for now only consider the case when one calls on one recipe at a time. So for now I will not try to provide a fix for when one does something like `make library tests check` (one can simply check `ifeq ($(words $(MAKECMDGOALS)), 1)`). We can append with more rules later.

Some recipes, such as `clean`, `distclean`, `uninstall` and `dist`, does not require `.d` files, and so we do not have to include them for these cases.

`library`, `shared` and `static` only depend on `[L]OBJS`. In this case we only have to include the corresponding `.d` files.

For `profile` and `check`, the case is a little bit more complex if we want to obtain something fast. I will assume that the recipe is `check`, but something similar goes for `profile`. As `check` depends on `library`, we cannot really exclude regular objects' and test executables' `.d` files. *This should not really be a problem as the checks takes a long time and we want to be rigorous here.*

However, if one sets `MOD`, we make a sketchy solution which is to only include `.d` files for the tests specified by `MOD`. In this case, we should really print a warning such as `$(warning Dependency tracking only set to cover the test executables of $(MOD).)`.

What is your opinion on this, @fredrik-johansson?

**Comment by albinahlback** [comment]
I will also fix a bug present in the current version of FLINT for dependency tracking when both static and shared are enabled.

**Comment by albinahlback** [comment]
I am done with

**Comment by albinahlback** [comment]
I think this is complete now. If you don't understand something about the code, I'd be glad to explain it.

Let me know when you are ready to merge it, and I will squash the commits.

**Comment by albinahlback** [comment]
> The dependency tracking seems to be off, e.g. `touch src/fmpz.h && make` no longer triggers a rebuild.

I cannot seem to reproduce this. Did you reconfigure?

**Comment by fredrik-johansson** [comment]
> I cannot seem to reproduce this. Did you reconfigure?

I did, but then I did it once again after ``make distclean`` and now it seems to work again.

I'm not sure if the module-only dependency tracking for ``make check MOD=`` is a good idea, but we can try and see how it works out.

The remaining cosmetic issue I'd like to see fixed is in some way displaying the current module when running ``make check``.

**Comment by albinahlback** [comment]
> I'm not sure if the module-only dependency tracking for `make check MOD=` is a good idea, but we can try and see how it works out.

Yeah, I think we definitely should think of another solution, but as of now I think we should merge it. I am currently squashing and renaming the commits.

**Comment by fredrik-johansson** [comment]
``make profile`` fails unless the profiling programs are compiled with ``-std=gnu99``.

I suppose instead of messing with separate CFLAGS we could just fix the programs (avoiding C++ comments, etc.).

**Comment by albinahlback** [comment]
> `make profile` fails unless the profiling programs are compiled with `-std=gnu99`.
> 
> I suppose instead of messing with separate CFLAGS we could just fix the programs (avoiding C++ comments, etc.).

I think so as well. Let me fix it.

**Comment by fredrik-johansson** [comment]
BTW, ``--output-sync=target`` is nice for when the tests pass, but it suppresses the output on failure. So for example instead of

    floor....FAIL!
    x = deg 4 [6, 5846006549322947058816851708631958633472849870848, 156057778423769613927561821959, 0, 5985579955690074030970874985941087669112180907708415] [0.04960830152309837019145348802184887525 +/- 2.20e-39] + [0.08592409871520289753759717036977766843 +/- 5.04e-39]*I

    n = 1

    n1 = 2

you just get

    floor....make: *** [Makefile:606: build/qqbar/test/t-floor_TEST_RUN] Aborted (core dumped)
    make: *** Waiting for unfinished jobs....

Do you know how to fix that? If it can be done, it would be nice to enable synced output by default if possible!

**Comment by albinahlback** [comment]
I did not care to remove the massive amount of unused variables.

**Comment by albinahlback** [comment]
Let me see if I can fix the supression of output on failure.

**Comment by albinahlback** [comment]
> BTW, `--output-sync=target` is nice for when the tests pass, but it suppresses the output on failure. So for example instead of
> 
> ```
> floor....FAIL!
> x = deg 4 [6, 5846006549322947058816851708631958633472849870848, 156057778423769613927561821959, 0, 5985579955690074030970874985941087669112180907708415] [0.04960830152309837019145348802184887525 +/- 2.20e-39] + [0.08592409871520289753759717036977766843 +/- 5.04e-39]*I
> 
> n = 1
> 
> n1 = 2
> ```
> 
> you just get
> 
> ```
> floor....make: *** [Makefile:606: build/qqbar/test/t-floor_TEST_RUN] Aborted (core dumped)
> make: *** Waiting for unfinished jobs....
> ```
> 
> Do you know how to fix that? If it can be done, it would be nice to enable synced output by default if possible!

Can you give me a MWE? I cannot seem to reproduce it completely:
```
$ cat src/thread_pool/test/t-test.c
#include <stdio.h>

int
main()
{
    printf("thread_pool/test...");
    fprintf(stderr, "FAIL!!\n");
    return 1;
}

$ make -j --output-sync=target check MOD=thread_pool
Makefile:397: Dependency tracking only set to cover the test executables of thread_pool.
  CC  thread_pool/test/t-test
FAIL!!
thread_pool/test...make: *** [Makefile:606: build/thread_pool/test/t-test_TEST_RUN] Error 1
make: *** Waiting for unfinished jobs....
  CC  thread_pool/test/t-thread_pool
```
However, if I flush every output, I always get
```
```
$ cat src/thread_pool/test/t-test.c
#include <stdio.h>

int
main()
{
    printf("thread_pool/test...");
    fflush(stdout);
    fprintf(stderr, "FAIL!!\n");
    fflush(stderr);
    return 1;
}

$ make -j --output-sync=target check MOD=thread_pool
Makefile:397: Dependency tracking only set to cover the test executables of thread_pool.
  CC  thread_pool/test/t-test
thread_pool/test...FAIL!!
make: *** [Makefile:606: build/thread_pool/test/t-test_TEST_RUN] Error 1
make: *** Waiting for unfinished jobs....
  CC  thread_pool/test/t-thread_pool
```

**Comment by fredrik-johansson** [comment]
Yes, flushing seems to do the job.

Some tests currently call ``fflush``, but not all.

Maybe we could change ``flint_abort()`` to do

    FLINT_NORETURN void flint_abort()
    {
        fflush(stdout);   /* make sure error messages get printed */
        (*abort_func)();
    }

and then remove the explicit fflushes from the test code?

**Comment by fredrik-johansson** [comment]
Yes, just showing which modules are being tested when running ``make check``.

The old version printed the module name as it entered each directory, so when seeing ``add....`` you'd know which module it belonged to.

Keeping the current parallel build, maybe it's possible to print the module name in front of each test program instead?

    fmpz add....PASS
    fmpz addmul....PASS
    fmpz addmul_si....PASS
    ...
    fmpq add....PASS
    ...

Of course, we could edit all the test files to change the print messages, but maybe this can be accomplished from the makefile.

**Comment by albinahlback** [comment]
Although it is possible, I really think it is the test files' responsibility. I wouldn't like to change it in the makefile.

**Comment by fredrik-johansson** [comment]
OK, I'll merge this as is and see how it works out.

**Pull request merged**
