### PR TITLE
Remove local inclusions

### PR DESCRIPTION
**Pull request by albinahlback**
Currently a lot of "unnecessary" inclusions are made, like including `X.h` in `X_mat.h` or similar things, when there is no need to.

This PR aims to reduce the number inclusions in each header to its minimum WITHOUT modifying the content of each header (which is necessary if one would like to further reduce the headers' complexity).

Mainly, building times should go down drastically, but developers relying on these headers in their own libraries should also see a reduction in compile time.

Here is a benchmark with `CFLAGS=-Wall`, ran via `time make -j`:
```
AFTER LOCAL REMOVAL (with fmpr !!!)
real    3m7.549s
user    10m30.554s
sys     1m36.361s

BEFORE REMOVAL (without fmpr)
real    3m58.834s
user    13m40.944s
sys     1m50.074s
```
and so it is obvious that the headers create a huge problem for the build time.

It remains to fix the tests.

Edit: Note, however, that for an optimal build time, inclusions in source files also has to be reduced. Currently, far too many files contained in the 'old' FLINT includes way too much.

### CODE REVIEW

**Comment by albinahlback** [comment]
I suppose that this can help multithreaded builds a bit as (to my understanding) IO is slower for multiple threads, so reducing the number of inclusions can help in this regard.

**Comment by fredrik-johansson** [comment]
Instead of doing the ``__GNUC__`` dance for math.h functions maybe we could define these once in double_extras.h.

At some point I want to include our own double precision transcendental functions instead of relying on libm anyway.

**Comment by albinahlback** [comment]
I think such a solution is prone to compiler errors. Suppose we have this code:
```c
#define exp __builtin_exp
#include <math.h>
#include <stdlib.h>
#include <stdio.h>

int
main(int argc, char ** argv)
{
    double x = strtod(argv[1], NULL);

    printf("exp(%f) = %f", x, exp(x));
    return 0;
}
```
This generates the following error on my system:
```
/usr/include/bits/mathcalls.h:95:1: error: expected ‘;’ before ‘extern’
   95 | __MATHCALL_VEC (exp,, (_Mdouble_ __x));
      | ^~~~~~~~~~~~~~
/usr/include/bits/mathcalls.h:95:1: error: expected ‘;’ before ‘extern’
   95 | __MATHCALL_VEC (exp,, (_Mdouble_ __x));
      | ^~~~~~~~~~~~~~
/usr/include/bits/mathcalls.h:95:1: error: expected ‘;’ before ‘extern’
   95 | __MATHCALL_VEC (exp,, (_Mdouble_ __x));
      | ^~~~~~~~~~~~~~
```
So if one where to do
```
#include "double_extras.h"
#include <math.h>
```
it would generate compiler errors.

**Comment by fredrik-johansson** [comment]
Yes, they'd have to be named ``d_exp``, etc.

**Comment by albinahlback** [comment]
> Yes, they'd have to be named `d_exp`, etc.

Well, that I am very open to do. But let's merge this first.

**Comment by fredrik-johansson** [comment]
Sure.

**Pull request merged**
