### PR TITLE
Try to fix Appveyor

### PR DESCRIPTION
**Pull request by albinahlback**
The error message we currently get in AppVeyor is very cryptic. Here is an attempt to fix it.

### CODE REVIEW

**Comment by albinahlback** [comment]
@fredrik-johansson I have tried everything I can now (tried to emulate Arb's CMakeLists.txt), and it never shows any proper error messages. If you have a solution I am all for it, but now I'm out of Microsoft tolerance haha.

**Comment by albinahlback** [comment]
One important note, however, is that you probably want to keep the changes in `qsieve/[factor/init].c`. MSVC did not like including `windows.h`, which was the culprit for all those errors in `qsieve.h`.

Now it just doesn't like linking.

**Comment by fredrik-johansson** [comment]
@isuruf Want to have a look at this?

**Comment by isuruf** [comment]
Forcing IPO in cmake at https://github.com/flintlib/flint2/blob/trunk/CMakeLists.txt#L309-L318 takes too much memory and gets killed.

**Comment by albinahlback** [comment]
> Forcing IPO in cmake at https://github.com/flintlib/flint2/blob/trunk/CMakeLists.txt#L309-L318 takes too much memory and gets killed.

Is that the problem though?

**Comment by isuruf** [comment]
> Is that the problem though?

That's the first problem. Removing IPO, builds the flint2 library, but building tests fail.
The problem is the removal of FLINT_DLL and ARB_DLL macros. `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` only work for functions and does not work for global data symbols. Previously `FLINT_DLL` was used for functions and data whereas `ARB_DLL` was used for global data only and relied on `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` to export the functions.
With the removal of the `_DLL` macros, the global data is not exported anymore.

**Comment by albinahlback** [comment]
If it's just the data it should be an easy fix. Will probably get around to doing it tomorrow. Thanks for your input!

**Comment by isuruf** [comment]
I've got a branch at https://github.com/isuruf/flint2/tree/fix_windows

**Comment by isuruf** [comment]
Can you merge my branch to yours?

There are only a few errors after that

> t-approx_dot.c.obj : error LNK2019: unresolved external symbol acb_dot_gauss_dot_cutoff referenced in function main
t-dot.c.obj : error LNK2019: unresolved external symbol acb_dot_gauss_dot_cutoff referenced in function main
t-mul_block.c.obj : error LNK2019: unresolved external symbol arb_mat_mul_block_min_block_size referenced in function main
t-exp_series.c.obj : error LNK2019: unresolved external symbol arb_poly_newton_exp_cutoff referenced in function main
t-gamma_taylor_tab.c.obj : error LNK2019: unresolved external symbol arb_hypgeom_gamma_coeffs referenced in function main
t-exp_series.c.obj : error LNK2019: unresolved external symbol acb_poly_newton_exp_cutoff referenced in function main
t-adjugate.c.obj : error LNK2019: unresolved external symbol _ca_methods referenced in function main

**Comment by albinahlback** [comment]
Yes, that's fine! Do you wanna add a copyright claimer to CMakeLists.txt? Mainly so we know who got the knowledge.

**Comment by albinahlback** [comment]
Isuru, would you be fine by replacing AppVeyor with the MSVC CI? I could also add a 32-bit checker if you'd like.

**Comment by isuruf** [comment]
> [Remove some FLINT_DLLs](https://github.com/flintlib/flint2/pull/1282/commits/ea58b46c21342d4a015c37aff4589487e7e78303)

Why? This would not work.

> Isuru, would you be fine by replacing AppVeyor with the MSVC CI? 

I'm not sure what you mean by MSVC CI.

> Do you wanna add a copyright claimer to CMakeLists.txt? Mainly so we know who got the knowledge.

Sure.

**Comment by albinahlback** [comment]
> Why? This would not work.

Oh, I thought `FLINT_DLL` was not supposed to be in the definition. How am I supposed to fix this?

> I'm not sure what you mean by MSVC CI.

I mean the Github action.

**Comment by isuruf** [comment]
> Oh, I thought FLINT_DLL was not supposed to be in the definition. How am I supposed to fix this?

Sorry. I made that comment before 9cef372c3e6c319b3bdff9c5fd9e65d0f1011449. 9cef372c3e6c319b3bdff9c5fd9e65d0f1011449 should fix all the linking errors.

At 9cef372c3e6c319b3bdff9c5fd9e65d0f1011449 we have only two errors

The following tests FAILED:
	3076 - src-gr-test-t-fmpz_mpoly_evaluate (SEGFAULT)
	3336 - src-ca_mat-test-t-exp (SEGFAULT)

**Comment by fredrik-johansson** [comment]
> 3076 - src-gr-test-t-fmpz_mpoly_evaluate (SEGFAULT)

Likely due to the test program allocating temporaries on the stack inside the main loop and overflowing the stack (a bunch of other gr test programs potentially suffer from this as well, and need to be fixed).

> 3336 - src-ca_mat-test-t-exp (SEGFAULT)

Don't really have a clue here.

**Comment by albinahlback** [comment]
I will put the responsibility on you, Fredrik! Do you want me to merge this for the time being? Will squash commits, add copyright to `CMakeLists.txt` and uncomment the rest in `CI.yml`.

**Comment by fredrik-johansson** [comment]
Sure, this can be merged.

**Pull request merged**
