### PR TITLE
Dan Schultz's fft_small

### PR DESCRIPTION
**Pull request by fredrik-johansson**
Just want to see what happens in CI for now.

@tthsqe12

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
@albinahlback  There's more FLINT cleanup to be done first, but maybe at some point you want to look at this?

The main thing to do here is to set up the build system so that we build/use ``fft_small`` only on systems where the relevant vector instructions are supported.

I suppose we also want to enable Dan's CFLAGS (``-O3 -fno-stack-protector -march=native``) specifically for the ``fft_small`` module.

**Comment by albinahlback** [comment]
> @albinahlback There's more FLINT cleanup to be done first, but maybe at some point you want to look at this?
> 
> The main thing to do here is to set up the build system so that we build/use `fft_small` only on systems where the relevant vector instructions are supported.
> 
> I suppose we also want to enable Dan's CFLAGS (`-O3 -fno-stack-protector -march=native`) specifically for the `fft_small` module.

I suppose that relevant vector instructions are AVX2 and AVX512 (and perhaps some specific version of this). This is very easy to check during configuration. And one can just extend the makerules with, say, some directories that contains their own CFLAGS. Should be easy.

**Comment by albinahlback** [comment]
Is there any reason to why one would set `-march=native` specifically for this module? I mean, it gives performance for FLINT as a whole. If we only set it for this module, it will still break other non-compatible CPU's.

**Comment by albinahlback** [comment]
I will work on this now.

**Comment by albinahlback** [comment]
Dan, I hope you are alive and well! :-) Do you remember any specifics on where you would like to use the optimization flag `-O3`, and perhaps some SIMD-instructions (AVX2, AVX512 etc.)? @tthsqe12

**Comment by albinahlback** [comment]
To be honest, although it might be good performance-wise, the code is sort of a mess in my opinion. I will see how much I am able to fix. Most of the problems stems from assuming the compiler is GCC-compatible and that the CPU has either AVX instructions or Neon instructions.

**Pull request merged**
