### PR TITLE
[DO NOT MERGE] Move everything to src/

### PR DESCRIPTION
**Pull request by albinahlback**
This has been needed for a long time IMO.

`.gitignore`, `Makefile.in`, `Makefile.subdirs` and `configure` are the only files whose content has been changed.

@fredrik-johansson see if you like this this concept. If you do, I have to change the CMake file as well.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Yes, I have thought about doing this.

Of course, this should wait until after the great mergening.

**Comment by albinahlback** [comment]
Sounds good.

**Comment by fredrik-johansson** [comment]
The ``profile`` and ``test`` directories should also go in ``src`` since they are the profile and test directories corresponding to ``.c`` files that happen to be in the top-level directory; they are not the locations of some library-wide profiling or test code.

Actually, I would like to move all the ``.c`` files in the top level directory to a ``flint`` module or something like that, with these profile and test directories place in that directory, so that they don't need to be special-cased by the build system.

**Comment by albinahlback** [comment]
Sounds good, missed that!

**Comment by albinahlback** [comment]
Is everything merged that should be merged?

**Comment by fredrik-johansson** [comment]
Sure.

**Pull request closed without merging**
