### PR TITLE
Remove unnecessary headers

### PR DESCRIPTION
**Pull request by albinahlback**
Remove unnecessary inclusions in header files and correct files according to this.

Note: I am not trying to change every source file or minimize headers. I am simply trying to correct the bloated headers without altering them too much and this is quite minimal for this goal.

### CODE REVIEW

**Comment by albinahlback** [comment]
I am done with actual source files. I will now fix the test code.

**Comment by albinahlback** [comment]
Most notably, FLINT will not include `stdio.h`, `stdlib.h`, `math.h`, `float.h` by default. In order to get printing functions that use `FILE` or `va_list`, users have to include `stdio.h`: **This is going to be documented**.

**Comment by fredrik-johansson** [comment]
I'm not sure about dropping ``stdio.h`` and ``stdlib.h`` from ``flint.h``. The printing functions are pretty commonly used, and it will be annoying if you have to insert the same boilerplate just to throw in a debug flint_printf.

**Comment by albinahlback** [comment]
> 

Why would we need to include `stdlib.h`? You can still call `flint_malloc`/whatever as usual.

**Comment by albinahlback** [comment]
You can still call `flint_printf` without including `stdio.h`.

**Comment by albinahlback** [comment]
You cannot, however, call `flint_fprintf` as that requires `FILE`. As the user intends to use `FILE` variables, I think it is very reasonable to not include it by default.

**Comment by fredrik-johansson** [comment]
I mean, to take a random example, you had to add

    #undef ulong
    #define ulong ulongxx /* ensure vendor doesn't typedef ulong */
    #include <stdio.h>
    #undef ulong

to nmod_mpoly_factor/mpolyv.c just so that function can use flint_printf. Not very pretty.

**Comment by albinahlback** [comment]
> I mean, to take a random example, you had to add
> 
> ```
> #undef ulong
> #define ulong ulongxx /* ensure vendor doesn't typedef ulong */
> #include <stdio.h>
> #undef ulong
> ```
> 
> to nmod_mpoly_factor/mpolyv.c just so that function can use flint_printf. Not very pretty.

No, that is to be able to use `nmod_mpoly_print_pretty` as it is inlined to `nmod_mpoly_fprint_pretty(stdout, A, x, ctx)`.

**Comment by albinahlback** [comment]
And I don't think it should be inlined.

**Comment by albinahlback** [comment]
I simply did it this way as the other PR, which dealt with de-inlining such things, was too large, partly because of this.

**Comment by albinahlback** [comment]
I think that FLINT is supposed to be viewed as a library, not the end-product. More "comfortable" programming purposes (such as including many headers, which might be used by some users) should be left to other applications such as Sage, Nemo and other C-utilities.

When I read
> FLINT is a C library of functions for doing basic arithmetic in support of computational number theory and other areas of computer algebra.

I do not read this as describing the "comfortable" way, but rather the minimal library [source](https://flintlib.org/doc/introduction.html).

**Comment by albinahlback** [comment]
I think the current state of this PR should pass the tests. Please let me know if anything can be improved.

**Comment by albinahlback** [comment]
Even though reducing build time was not the goal of this PR (the main goal was to reduce dependencies for each header), I managed to reduce it anyway by 16 %:
```
## Old timings
$ time make
...
real    6m39.751s
user    5m49.719s
sys     0m48.298s

## New timings
$ time make
real    5m33.887s
user    4m54.681s
sys     0m38.090s
```

**Comment by albinahlback** [comment]
I don't know why Windows fail when using the shared library version of FLINT. For the first time I tried out CMake on FLINT, and my machine is able to create the library, create the tests, and run all the tests, without any problems.

The issue is as follows. After it has created the library, it starts to create all the tests. No problem creating the majority of the tests. The problems seems to arise from creating the executable for `fmpz_poly/t-hensel_lift.c` due to
```
error LNK2019: unresolved external symbol __imp_nmod_poly_is_squarefree referenced in function main
```
For static libraries, it seems to work fine.

I have double checked these test files and the referenced source files, but I can't seem to find any problem. Furthermore, `nmod_poly_is_squarefree` gets linked without any problem. Perhaps the problem stems from CMake, Windows or perhaps some wrong implementation of the `CMakeLists.txt` for Windows. I don't know at this point.

**Comment by albinahlback** [comment]
@wbhart, who is responsible for the CMake utilities in FLINT?

**Comment by fredrik-johansson** [comment]
nmod_poly_is_squarefree is in the nmod_poly_factor module rather than in nmod_poly. The build logs don't show any warnings about missing prototypes though?

**Comment by albinahlback** [comment]
Sorry for not being clear, the problem is as follows.

In the fourth latest commit named "[Fix possible bug in mpoly.h](https://github.com/wbhart/flint2/pull/1142/commits/db86b67c464e7c5d49bfcedeb35a4b760da048b6)", you can see that both MinGW and Appveyor fails due to undefined references. Here both MinGW and Appveyor builds shared libraries (in later commits I tested to switch to building static libraries).

It seems to be the case that only shared libraries for Windows fails the test; For static libraries it seems to pass (except for Appveyor, where building static libraries takes more time than Appveyor's building time limit).

Note that no platform complains about building `nmod_poly_factor/is_squarefree.c` in any way. Also note the necessary headers are included in this file and the test file that failed to compile.

Anyway, I'm really puzzled about this. I would really like to merge this, but I wouldn't wish this on Windows users.

**Comment by wbhart** [comment]
For me the logs for appveyor seem to be incomplete. In fact it looks like something timed out after one hour in both cases.

I don't know what is causing the issue you are referring to. How is nmod_poly.h included now? Is it included in nmod_poly_factor.h?

I notice in the diff that there are quite a few cases of things like

```
#   define ulong mp_limb_t
```

with spaces after the hash. I think it would be preferable to have no spaces after hashes, i.e.

```
#define ulong mp_limb_t
```

I'm not clear if this is a preexisting issue or not, but perhaps you could take the opportunity to correct it either way.

**Comment by albinahlback** [comment]
> For me the logs for appveyor seem to be incomplete. In fact it looks like something timed out after one hour in both cases.

Yes, that is for the latest commits, where I switched to building static libraries instead of shared libaries. You should look at the tests for the commit named "Fix possible bug in mpoly.h".

> I don't know what is causing the issue you are referring to. How is nmod_poly.h included now? Is it included in nmod_poly_factor.h?

Yes, `nmod_poly.h` is now included in `nmod_poly_factor.h`, while `nmod_poly_factor.h` is **not** included in `nmod_poly.h`.

> 
> I notice in the diff that there are quite a few cases of things like
> 
> ```
> #   define ulong mp_limb_t
> ```
> 
> with spaces after the hash. I think it would be preferable to have no spaces after hashes, i.e.
> 
> ```
> #define ulong mp_limb_t
> ```
> 
> I'm not clear if this is a preexisting issue or not, but perhaps you could take the opportunity to correct it either way.

I can fix this if we resolve the other issue. I think it's more readable, but if you do not think so, I will change to your way.

**Comment by wbhart** [comment]
I don't think we should make arbitrary changes to the coding style, so it should be changed back to the existing style, which is quite standard.

As for what is causing the issue you are seeing, I don't have any insight. There seem to be test failures in the preceding commits as well so I have no idea where the problem has been introduced.

**Comment by albinahlback** [comment]
> I don't think we should make arbitrary changes to the coding style, so it should be changed back to the existing style, which is quite standard.

I have never seen that standard outside of FLINT, but yes, we shouldn't make that change if not everyone is comfortable with it.

> As for what is causing the issue you are seeing, I don't have any insight. There seem to be test failures in the preceding commits as well so I have no idea where the problem has been introduced.

Yeah, as mentioned earlier, it is very hard to make small commits that passes the tests when changing these things. Hence it might be hard to track the problem.

However, everything passes for all the Unix-type systems, and it feels like either CMakeLists.txt has some bug (note that I never changed the directory structure) or perhaps I've triggered some bug in Windows-systems. I honestly don't know.

**Comment by isuruf** [comment]
Try changing https://github.com/wbhart/flint2/blob/c646c59e6472ddc5688691dfaf21f9f2c04a600a/nmod_poly_factor/is_squarefree.c#L12 to `nmod_poly_factor.h`

**Comment by albinahlback** [comment]
> Try changing
> 
> https://github.com/wbhart/flint2/blob/c646c59e6472ddc5688691dfaf21f9f2c04a600a/nmod_poly_factor/is_squarefree.c#L12
> to `nmod_poly_factor.h`

Thanks for helping, I really appreciate it! I will try this out, although I see no reason to why that should be needed here as all the functions within this file is contained within `nmod_poly.h`.

**Comment by isuruf** [comment]
> error LNK2019: unresolved external symbol __imp_nmod_poly_is_squarefree referenced in function main

`__imp_nmod_poly_is_squarefree` is the mangled name for `FLINT_DLL nmod_poly_is_squarefree`. This symbol being missing is an indication that when `libflint.dll` was compiled `nmod_poly_is_squarefree` was not compiled with `FLINT_DLL`.

Note that,
```
FLINT_DLL nmod_poly_is_squarefree;
int
nmod_poly_is_squarefree(const nmod_poly_t f)
{
    return _nmod_poly_is_squarefree(f->coeffs, f->length, f->mod);
}
```
is equivalent to
```
FLINT_DLL nmod_poly_is_squarefree;
FLINT_DLL int
nmod_poly_is_squarefree(const nmod_poly_t f)
{
    return _nmod_poly_is_squarefree(f->coeffs, f->length, f->mod);
}
```
and generates the correct mangled name `__imp_nmod_poly_is_squarefree`.

However just
```
nmod_poly_is_squarefree;
int
nmod_poly_is_squarefree(const nmod_poly_t f)
{
    return _nmod_poly_is_squarefree(f->coeffs, f->length, f->mod);
}
```
generates the incorrect mangled name `nmod_poly_is_squarefree`.

**Comment by albinahlback** [comment]
Seems like it is going to pass all the tests. What remains is documenting this, which I will do in a week or so.

**Comment by wbhart** [comment]
Thanks very much @isuruf !!

I thought it had to do with FLINT_DLL but after spending quite some time on it, I couldn't see the issue. I really appreciate that you tracked this down.

**Comment by wbhart** [comment]
> > I don't think we should make arbitrary changes to the coding style, so it should be changed back to the existing style, which is quite standard.
> 
> I have never seen that standard outside of FLINT, but yes, we shouldn't make that change if not everyone is comfortable with it.

I am not sure if we are talking about the same thing.

Here is a random tutorial page on #define:

https://www.techonthenet.com/c_language/constants/create_define.php

As you can see from the examples, there are no spaces after the hash. I am quite sure I can multiply examples. I didn't even know putting spaces after the hash was possible. I've never seen it before.

**Comment by wbhart** [comment]
Ok, I see that placing a space after the hash was only a problem for pre-ANSI C compilers. It seems there are two conventions for indenting #defines and the like. One is the convention you have used, the other is to indent the hash as well.

The main reason to indent the hash as well is apparently because some syntax highlighters don't recognise it otherwise.

So I will let @fredrik-johansson make a decision on what he prefers here. I now no longer have a specific preference. But I think we should document it in the code_conventions.txt file to keep things uniform.

**Comment by fredrik-johansson** [comment]
Definitely no space in `#define` for me. I see no advantage and it's just going to confuse people and tools.

**Comment by fredrik-johansson** [comment]
flint_printf("p = %wu; exp = %wu\n", f->p, f->exp);

    v

    printf("p = " WORD_FMT "u; exp = " WORD_FMT "u\n", f->p, f->exp);

Let's not do this. It's way less readable. We added ``flint_printf`` et al. for a reason.

Gentle reminder to keep PRs focused on one thing ;-)

**Comment by albinahlback** [comment]
> ```
> flint_printf("p = %wu; exp = %wu\n", f->p, f->exp);
> 
> v
> 
> printf("p = " WORD_FMT "u; exp = " WORD_FMT "u\n", f->p, f->exp);
> ```
> 
> Let's not do this. It's way less readable. We added `flint_printf` et al. for a reason.
> 
> Gentle reminder to keep PRs focused on one thing ;-)

Thanks for you feedback, I truly appreciate it! I will revert this change, I think I will change this in another PR.

**Comment by albinahlback** [comment]
> Ok, I see that placing a space after the hash was only a problem for pre-ANSI C compilers. It seems there are two conventions for indenting #defines and the like. One is the convention you have used, the other is to indent the hash as well.
> 
> The main reason to indent the hash as well is apparently because some syntax highlighters don't recognise it otherwise.
> 
> So I will let @fredrik-johansson make a decision on what he prefers here. I now no longer have a specific preference. But I think we should document it in the code_conventions.txt file to keep things uniform.

I think the `# define`-style comes from GNU. I think I've only looked at GMP and GNU headers. I now see that other headers use spaces before the hash symbol. I will change it.

**Comment by albinahlback** [comment]
I've looked through all 1200 files (yes, that was exhaustive), and fixed the things that was not necessary. However, I let some things be, as `flint_printf("%li", variable)` is incorrect when variable is a slong (for this I wrote `printf(WORD_FMT "d", variable)` instead).

**Comment by albinahlback** [comment]
I think this branch broke as some new commits to trunk got merged. Will have to fix that another day.

**Comment by wbhart** [comment]
> I've looked through all 1200 files (yes, that was exhaustive), and fixed the things that was not necessary. However, I let some things be, as `flint_printf("%li", variable)` is incorrect when variable is a slong (for this I wrote `printf(WORD_FMT "d", variable)` instead).

For `slong` the correct thing is `flint_printf("%wd", variable)`. Please use the proper `flint_printf` function. It exists for a reason. I have no idea at all what the `printf` does that you are proposing. Let's not confuse our users with stuff like that!

**Comment by albinahlback** [comment]
`printf(WORD_FMT "d", myslong)` is equivalent to `flint_printf("%wd", myslong)`. It's just faster.

**Comment by albinahlback** [comment]
Please merge as soon as 2.9 is released.

**Comment by albinahlback** [comment]
Don't know why, but GCC for Cygwin does not seem to like ulong at all. Define and undef won't work, even with `-U` and `-D` flag for GCC. For some unknown reason the inclusion of `sys/types.h` in `flint.h` makes it work.

**Comment by fredrik-johansson** [comment]
I'm not 100% certain that removing stdio.h is a good idea. Now you have to include it in all test files anyway, it becomes less convenient to insert a debug printf in a random file, and probably some external users will be affected by this as well...

Other than that, well, there are a lot of changes here so it's not an easy PR to review...

**Comment by edgarcosta** [comment]
I am also not sure about removing `stdio.h`.
It has many convenient benefits as @fredrik-johansson pointed out, but more importantly, I find the idea of having to include `stdio.h` before any FLINT header to be extremely counterintuitive.
For me, FLINT is a system library, and I would never expect the order of system headers to matter, so much, that many code styles recommend you to have these sorted alphabetically.

**Pull request closed without merging**
