### PR TITLE
Clean up Nemo CI, add soname for v2.8.5 to configure

### PR DESCRIPTION
**Pull request by albinahlback**
Solves #1121.

### CODE REVIEW

**Comment by albinahlback** [comment]
Seems to work as intended.

**Comment by wbhart** [comment]
We really need to get Flint 2.9 out, then there's a whole pile of Nemo PRs waiting to be merged which require the new Flint to work.

**Comment by albinahlback** [comment]
> We really need to get Flint 2.9 out, then there's a whole pile of Nemo PRs waiting to be merged which require the new Flint to work.

This doesn't change any executables, only changes CI and adds comment in `configure`. Hence, this is not urgent at all. :-)

**Comment by tthsqe12** [comment]
The main binary change in flint 2.9 is - backed my popular demand - a rearrangement of the fmpq_poly struct, which means everything downstream needs to be recompiled.

**Pull request closed without merging**
