### PR TITLE
Maximally reduce some fq_* headers

### PR DESCRIPTION
**Pull request by albinahlback**
The ones reduced are:
- `fq(_nmod/_zech).h`
- `fq(_nmod/_zech)_vec.h`
- `fq(_nmod/_zech)_mat.h`
- `fq(_nmod/_zech)_poly.h`
- `fq(_nmod/_zech)_poly_factor.h`
- `fq(_nmod/_zech)_embed.h`

Edit: I know I could've made this PR a little bit smaller, I think I could've kept it to `fq(_nmod/_zech).h` only.

### CODE REVIEW

**Comment by albinahlback** [comment]
Oh wait, I have to include the new `*_types.h` headers in Makefile.in

**Comment by albinahlback** [comment]
To be clear here (or rather, stating that I was unclear in previous PR:s (although it is stated in the commit messages)): I have not deprecated any functions here.

**Comment by fredrik-johansson** [comment]
Looks OK.

**Comment by fredrik-johansson** [comment]
It is worth noting that this led to some performance regressions, presumably due to de-inlining.

For example, before one had

```
$ time build/gr/test/t-fq
fq.... PASS

real	0m1,803s
user	0m1,795s
sys	0m0,008s
```

and after,

```
$ time build/gr/test/t-fq
fq.... PASS

real	0m1,929s
user	0m1,925s
sys	0m0,004s
```

**Comment by albinahlback** [comment]
Yes, that should definitely be investigated. Do you know how much was *actually* being inlined before? Take `fq_default` for example: I'm unsure of how much is actually inlined due to the large function bodies. It may be the case that the functions are only closer in memory to the main function code.

**Comment by albinahlback** [comment]
My thought process has been to allow inlining for the basic types (that is `ulong`, `nmod_t`, `fmpz_t` etc.), but in general disallow inlining the more complex types (polynomials, matrices etc.). I saw `fq` as synonymous with `fmpz_poly`, but perhaps it is good to inline it.

**Comment by fredrik-johansson** [comment]
Hold on, I was being stupid. The difference was due to compiling with ``-funroll-loops`` disabled on the old branch (yes, ``-funroll-loops`` makes ``fq`` code slower).

Still, there are methods in the last commits that probably should be inlined again, like simple accessors (e.g. ``fmpz_poly_degree``), maybe ``init`` methods (most are just zeroing the structs, which the compiler potentially can optimize when batched for several inits). But this probably isn't a big deal for now.

**Comment by albinahlback** [comment]
> Hold on, I was being stupid. The difference was due to compiling with `-funroll-loops` disabled on the old branch (yes, `-funroll-loops` makes `fq` code slower).

We should definitely unroll every loop ;-)

> Still, there are methods in the last commits that probably should be inlined again, like simple accessors (e.g. `fmpz_poly_degree`), maybe `init` methods (most are just zeroing the structs, which the compiler potentially can optimize when batched for several inits). But this probably isn't a big deal for now.

Yeah, I think so as well.

**Pull request merged**
