### PR TITLE
Fix mistakes

### PR DESCRIPTION
**Pull request by ivan-pan**
Some further corrections. I am unsure what is meant here:

- `then a heuristic LLL a full precision floating point LLL` (fmpz_lll.rst)
- `of polynomials an array of links` (fmpz_poly.rst)

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
>     * `then a heuristic LLL a full precision floating point LLL` (fmpz_lll.rst)

Something like "then a heuristic LLL followed by a full precision floating point LLL if required" maybe? Though I'm not sure that's what the code does.

>     * `of polynomials an array of links` (fmpz_poly.rst)

"of polynomials and an array of" probably?

**Comment by ivan-pan** [comment]
Done.

**Comment by fredrik-johansson** [comment]
Sorry about leaving this hanging. Could you resolve the conflicts? I tried to do this with the web editor but I'm not sure if it lets me do a squashed merge after.

**Comment by ivan-pan** [comment]
Resolved now.

**Comment by fredrik-johansson** [comment]
Excellent, thank you!

**Pull request merged**
