### PR TITLE
Maximally reduce inclusions in `nmod.h`, `nmod_vec.h`, `nmod_mat.h` and `nmod_poly.h`

### PR DESCRIPTION
**Pull request by albinahlback**
...and in their respective sources.

I did change some other headers as well. @fredrik-johansson can you check all of the headers so that it looks okay?

I also made one inlined function to a macro in order to avoid including some file. The function was undocumented (I don't recall what it was called).

I only have to fix the inclusions in the test files.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
I don't understand the change to fq_templates/multiplicative_order.c

Why is the is_zero test no longer done before initializing tmp and ord_fact? (Indeed, there seems to be a potential memory leak now as these don't get cleared in the is_zero branch.)

Instead of making _nmod_mat_set_mod a macro, you could make it a non-inline function.

Likewise for nmod_mat_is_zero_row, nmod_poly_equal; these don't need to be inline.

Otherwise this looks fine.

**Comment by albinahlback** [comment]
It should be complete in all other regards (assuming the tests passes).

**Comment by fredrik-johansson** [comment]
> > Actually, I don't see a reason why it should be hidden. If you don't mind, I propose renaming it to `nmod_mat_set_mod`, changing the implementation to call `nmod_init` instead of duplicating that code, and documenting it as a public method.
> 
> Without being too long striped (old Swedish saying), when I started out with FLINT and its surroundings, I thought GMP was a weird library because the majority of the library is internals only. However, now I have noticed that feature creeping is much easier when everything is public as nothing can be removed without breaking compatibility.
> 
> Basically I think it needs a good reason to why it should be public. I don't see why you would change the modulus after initializing the matrix, but if you do need it, you could just hack it by doing `nmod_init(mat->mod, n)`. Currently `_nmod_mat_set_mod` does not change elements, which one perhaps would expect it to do. After calling `_nmod_mat_set_mod` the element may no longer be canonical.

Changing the modulus is as rather useful feature as it allows reusing the matrix storage in multimodular algorithms (you can see how it is done in some ``fmpz_mat`` and ``fmpq_mat`` functions). If we designed ``nmod_mat`` today it would have a separate context object, but this is not easy to change today for compatibility reasons. Anyway, it's easy as you say to access the ``nmod`` structure manually, so it doesn't matter much what we do with this particular function.

About the broader question of private/public interfaces: FLINT's users include people who do want access to the internal implementation because they are developing cutting-edge research software, and equally importantly, it removes a barrier between developing code that uses FLINT and developing code for FLINT itself. GMP's choice to hide most of its internals is actually a limitation for us which forces us to reimplement (sometimes worse) much of their functionality.

**Comment by albinahlback** [comment]
Alright, I'll write it to a new file.

**Comment by fredrik-johansson** [comment]
Anyway, positive review assuming that the tests pass.

**Pull request merged**
