### PR TITLE
Add `-impl.h` headers

### PR DESCRIPTION
**Pull request by albinahlback**
This is the first step towards improving building time.

I had to merge #1142 in order to not create conflicts. Probably should have rebased instead. I think the number of files and lines changed should change after that PR has been merged.

Basically for every directory I did
```
sed -i "#include [\"<]\w+\.h" *.c
sed -i "/#define ulong/d" *.c
sed -i "/#undef ulong/d" *.c
```
plus some sed-command for inserting `#include "mydir-impl.h` after the first `*/` (i.e. right after the copyright).

This should work for compiling both concatenated and individual source files.

As parts of this PR contains commits from #1142, I'd just like to clarify that the commits that are relevant are

- commits with suffix `-impl.h`
- the commit "[Move all inlines files to inlines.c](https://github.com/wbhart/flint2/pull/1156/commits/f97b6a1af414799c0ba7fffa5a63d2727a034661)"
- the commit "[Fix badly indented code generating warning](https://github.com/wbhart/flint2/pull/1156/commits/49f6e91689fb09b121bfbb096cb7b815220d016f)"
- the commit "[Add dummies for empty repositories](https://github.com/wbhart/flint2/pull/1156/commits/13288fe23997a29dfb85acdbaed325ba50395daf)"

If you are going to review this code, please go through individual commits instead of every file changed.

Edit: Will fix this PR after #1142 has been merged.

### CODE REVIEW

**Comment by tthsqe12** [comment]
Is this the branch that is supposed to have faster compile times? If so, under what conditions?  i.e. - The whole library? Incremental changes?

**Comment by albinahlback** [comment]
> Is this the branch that is supposed to have faster compile times? If so, under what conditions? i.e. - The whole library? Incremental changes?

No, this is a prerequisite in order to concatenate source files which will be used to reduce the compile times. So nothing exciting happening here, although it is quite nice to have some implementation headers.

**Comment by fredrik-johansson** [comment]
I should probably reiterate that a radical overhaul like concatenating all source files is far less likely to be merged than more conservative changes.

What is your plan for the separation between foo.h and foo-impl.h?

**Comment by albinahlback** [comment]
`foo-impl.h` is supposed to contain (very) internal functions and headers. So pretty much as currently written.

**Comment by tthsqe12** [comment]
> prerequisite in order to concatenate source files 

There are several obstacles to blindly concatenating all of the source files:
- local functions, static data, etc. with conflicting names
- where is the concatenated file stored? is it temporary? Surely futures developers aren't going to be editing one hug c file in the fmpz dir?
- Currently changing one file in one module results in a very fast rebuild of the library. I would say incremental build times are far more important than clean builds.

**Comment by albinahlback** [comment]
> There are several obstacles to blindly concatenating all of the source files:
> 
>     * local functions, static data, etc. with conflicting names

This is dealt with by doing `#define function myfunction` and then `#undef function`. I've also discovered some function multiplicities, so this PR also removes some of these.

>     * where is the concatenated file stored? is it temporary? Surely futures developers aren't going to be editing one hug c file in the fmpz dir?

It is not temporary per say, it will basically be a file on the form
```c
#include "fmpz/add.c"
#include "fmpz/aors_ui.c"
...
#include "fmpz/xor.c"
```
That's it. Such files will be created by the makefile. And it should still be possible to compile every individual source file by themself. I do not intend to concatenate all the files. 
 
>     * Currently changing one file in one module results in a very fast rebuild of the library. I would say incremental build times are far more important than clean builds.

This will be just as fast. And I would assume that this would be even faster due to the makefile calling `$(MAKE)` for subdirs, which takes a lot of times.

Compiling concatenated files is actually superfast. The problem is the amount of files being compiled.

**Comment by albinahlback** [comment]
But just to be clear, this PR is still independent of changes on the makefile. I still think that `-impl` headers are a good thing (however, with FLINT's philosophy in mind they have to be used in moderation).

**Pull request closed without merging**
