### PR TITLE
Try to get AppVeyor working again

### PR DESCRIPTION
**Pull request by albinahlback**
Touched too much in #1249.

Will try to get AppVeyor to work again.

### CODE REVIEW

**Comment by albinahlback** [comment]
I believe that the problem arises from not using `FLINT_DLL` for `flint_test_multiplier`. Debugging for Windows is really super easy...

**Comment by fredrik-johansson** [comment]
> Edit: I really hope we do not have to prepend FLINT_DLL to every function in Arb, Calcium and GR...

Does adding

        set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS yes)

to CMakeLists.txt solve the problem? (And if so, maybe we can remove FLINT_DLL altogether.)

**Comment by fredrik-johansson** [comment]
In fact, I believe ``CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`` solves the problem for exporting all functions automatically.

We still need ``FLINT_DLL`` for global variables.

**Comment by albinahlback** [comment]
Yes, the problem was not using `FLINT_DLL`! You can even see that MinGW proceeds further! Let's see, I will first try to migrate the MSVC checks to Github.

**Comment by albinahlback** [comment]
I couldn't get it to work. Perhaps we need to write FLINT_DLL everywhere...

**Comment by fredrik-johansson** [comment]
Did you try using the Arb CMakeLists.txt and appveyor.yml? Appveyor is still working for the Arb repo.

**Comment by albinahlback** [comment]
Alright, I'll try!

**Pull request closed without merging**
