### PR TITLE
Move everything to `src/`

### PR DESCRIPTION
**Pull request by albinahlback**
~~For ease of checking this PR, check each commit individually.~~

~~A bug that will be introduced is that if the directory or any superdirectory is being renamed, the makefile will not work, and one have to configure FLINT again. This is due to `FLINT_DIR`, `SRC_DIR` and `BUILD_DIR` being set during the configuration.~~

I also fixed bug: now `EXEEXT` can be something that is not a nullstring.

### CODE REVIEW

**Comment by albinahlback** [comment]
Apart from MinGW, the tests should pass now. @fredrik-johansson can you check so that `valgrind` and such things work as intended?

**Comment by fredrik-johansson** [comment]
The Cygwin/GCC tests also fail.

**Comment by albinahlback** [comment]
Let me know if you'd like me to squash the commits and/or rename them.

**Comment by fredrik-johansson** [comment]
> Let me know if you'd like me to squash the commits and/or rename them.

Yes, this would be good squashed.

@isuruf Could you review this?

Maybe some more downstream users should have a look too... @fingolfin @thofma?

**Comment by fingolfin** [comment]
I don't expect this to cause a serious problem for us.

**Comment by albinahlback** [comment]
Don't know how to rebase properly when I merged in the middle of my commits in this branch, so commit `ba03015` and `cc634cb` shows up here as well. Anyway, the commits are now squashed with a more refined commit message.

**Comment by albinahlback** [comment]
But please, make sure that `make valgrind` works as intended (I haven't ran this myself).

**Comment by fredrik-johansson** [comment]
A bug: ``make check MOD=fmpz`` does not work after a clean build.

Indeed, the build files seem to end up in ``build/test`` rather than ``build/test/ulong_extras``.

**Comment by fredrik-johansson** [comment]
``make examples`` also failing:

    gcc: fatal error: input file ‘examples/bernoulli.c’ is the same as output file
    compilation terminated.
    make: *** [Makefile:201: examples] Error 1

**Comment by albinahlback** [comment]
This is a complete list of what I have checked:
```
make
make check [MOD=...]
make install
make profile [MOD=...]
make examples
```
I did not run `make valgrind` or `make tune`.

**Comment by fredrik-johansson** [comment]
``make valgrind`` fails because the module names are missing from the path:

```
    CC   /test/t-abs
test/t-abs.c:101:1: fatal error: opening dependency file /home/fredrik/src/flint5/flint2/build//test/t-abs.d: No such file or directory
  101 | }
      | ^
compilation terminated.
make[1]: *** [/home/fredrik/src/flint5/flint2/Makefile.subdirs:99: /home/fredrik/src/flint5/flint2/build//test/t-abs] Error 1
```

**Comment by fredrik-johansson** [comment]
Can you resolve the conflict?

**Comment by fredrik-johansson** [comment]
I noticed that the links to the library changed from relative to absolute paths:

Before:

    lrwxrwxrwx   1 fredrik fredrik       18 mars   2 19:21 libflint.so -> libflint.so.17.0.0
    lrwxrwxrwx   1 fredrik fredrik       18 mars   2 19:21 libflint.so.17 -> libflint.so.17.0.0
    -rwxrwxr-x   1 fredrik fredrik 71692552 mars   2 19:21 libflint.so.17.0.0

After:

    lrwxrwxrwx 1 fredrik fredrik       50 mars   2 20:59 libflint.so -> /home/fredrik/src/flint2/libflint.so.17.0.0
    lrwxrwxrwx 1 fredrik fredrik       50 mars   2 20:59 libflint.so.17 -> /home/fredrik/src/flint2/libflint.so.17.0.0
    -rwxrwxr-x 1 fredrik fredrik 71685176 mars   2 20:59 libflint.so.17.0.0

This breaks installing, because the installed libflint.so will refer back to the build directory...

**Comment by albinahlback** [comment]
fixar snabbt

**Comment by fredrik-johansson** [comment]
Looks still broken.

**Comment by albinahlback** [comment]
I completely reverted it to the previous use of `ln`. It won't be PWD-independent, but whatever.

**Comment by fredrik-johansson** [comment]
OK, let's try this much needed cleanup.

**Comment by thofma** [comment]
Sorry for the late reply! This looks good, thanks for checking with us.

**Pull request merged**
